export { default as EventList } from "./event/EventList"
export { default as Event } from "./event/event"
export { default as Team } from "./event/team"
export { default as Console } from "./console/console"
export { default as Signup } from "./auth/login/signup"
export { default as Signin } from "./auth/login/signin"
export { default as Documentation } from "./documentation"
export { default as Media } from "./media/media"
export { default as Upload } from "./media/upload"
export { default as Talks } from "./user/talks/talks"
export { default as Deck } from "./user/talks/deck/deck"
export { default as Mobile } from "./mobile/mobile"
export { default as Preferences } from "./settings/preference.page"
export { default as Schedule } from "./event/schedule/schedule"

//Todo: Naming conflict here . UserTalks and EventTalks --->
export { default as ScheduledTalks } from "./event/schedule/talks"

export { default as CreateEvent } from "./forms/event.form"
export { default as AuthForm } from "./forms/login.form"
export { default as TaskForm } from "./forms/task.form"
export { default as TeamForm } from "./forms/team.form"
