export { default as Header } from "./header/header"
export { default as Footer } from "./footer"
export { default as Loader } from "./loaders"
export { default as Detail } from "./detail"
export { default as ResolutionError } from "./ResolutionError"
export { default as Panes } from "./panes/pane"
export { default as SettingsPane } from "./panes/settings"
export { default as Switch } from "./switch"
export { default as Checkbox } from './checkbox'
export { default as Tip } from './tip'
